"""empty message

Revision ID: 1fb8a1776a28
Revises: b35c2798be77
Create Date: 2025-05-16 18:03:31.843747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '1fb8a1776a28'
down_revision: Union[str, None] = 'b35c2798be77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=512),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1152),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1152),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=512),
               existing_nullable=True)
    # ### end Alembic commands ###
