"""image phash index

Revision ID: 4541416a7914
Revises: 350a6eae3416
Create Date: 2025-05-16 22:51:53.714007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4541416a7914'
down_revision: Union[str, None] = '350a6eae3416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('image_phash_key', 'image', type_='unique')
    op.create_index(op.f('ix_image_phash'), 'image', ['phash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_phash'), table_name='image')
    op.create_unique_constraint('image_phash_key', 'image', ['phash'])
    # ### end Alembic commands ###
