"""add embedding vector to image

Revision ID: 47a5ce1d17bb
Revises: b14146e66dd7
Create Date: 2025-05-16 04:00:17.614333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47a5ce1d17bb'
down_revision: Union[str, None] = 'b14146e66dd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'keywords')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('keywords', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
