"""empty message

Revision ID: 60b429f5f34f
Revises: ed9a97d65548
Create Date: 2025-05-16 00:34:44.562175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60b429f5f34f'
down_revision: Union[str, None] = 'ed9a97d65548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sticker_pack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sticker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.Column('sticker_pack_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.ForeignKeyConstraint(['sticker_pack_id'], ['sticker_pack.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id'),
    sa.UniqueConstraint('sticker_pack_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sticker')
    op.drop_table('sticker_pack')
    # ### end Alembic commands ###
