"""add embedding vector to image

Revision ID: b14146e66dd7
Revises: bb83ae41a70f
Create Date: 2025-05-16 03:40:22.296950

"""
from typing import Sequence, Union

import pgvector.sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b14146e66dd7'
down_revision: Union[str, None] = 'bb83ae41a70f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'embedding')
    # ### end Alembic commands ###
