"""inline_usage

Revision ID: b35c2798be77
Revises: 47a5ce1d17bb
Create Date: 2025-05-16 17:14:46.046780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b35c2798be77'
down_revision: Union[str, None] = '47a5ce1d17bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_search_data_text', 'image', ['text'], unique=False, postgresql_using='gist', postgresql_ops={'text': 'gist_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_search_data_text', table_name='image', postgresql_using='gist', postgresql_ops={'text': 'gist_trgm_ops'})
    op.drop_table('image_usage')
    # ### end Alembic commands ###
