"""image.tg_ref

Revision ID: b5ea3879404a
Revises: b35c2798be77
Create Date: 2025-05-16 18:44:07.314039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5ea3879404a'
down_revision: Union[str, None] = 'b35c2798be77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('tg_ref', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'tg_ref')
    # ### end Alembic commands ###
