"""empty message

Revision ID: c5cefe557518
Revises: ed9a97d65548
Create Date: 2025-05-16 01:35:29.985419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5cefe557518'
down_revision: Union[str, None] = 'ed9a97d65548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sticker_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sticker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.Column('sticker_pack_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.ForeignKeyConstraint(['sticker_pack_id'], ['sticker_set.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id'),
    sa.UniqueConstraint('sticker_pack_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sticker')
    op.drop_table('sticker_set')
    # ### end Alembic commands ###
