"""init

Revision ID: ca43c9d79693
Revises:
Create Date: 2025-04-17 22:36:16.628758

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca43c9d79693'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('create extension if not exists pg_trgm')
    op.create_table(
        'channel',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'image',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('sha256', sa.String(), nullable=False),
        sa.Column('text', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('sha256'),
    )
    op.create_index(
        'ix_search_data_text',
        'image',
        ['text'],
        unique=False,
        postgresql_using='gist',
        postgresql_ops={'text': 'gist_trgm_ops'},
    )
    op.create_table(
        'channel_message',
        sa.Column('channel_id', sa.BigInteger(), nullable=False),
        sa.Column('message_id', sa.Integer(), nullable=False),
        sa.Column('image_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['channel_id'],
            ['channel.id'],
        ),
        sa.ForeignKeyConstraint(
            ['image_id'],
            ['image.id'],
        ),
        sa.PrimaryKeyConstraint('channel_id', 'message_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channel_message')
    op.drop_index(
        'ix_search_data_text',
        table_name='image',
        postgresql_using='gist',
        postgresql_ops={'text': 'gist_trgm_ops'},
    )
    op.drop_table('image')
    op.drop_table('channel')
    # ### end Alembic commands ###
