"""empty message

Revision ID: ed9a97d65548
Revises: f69b556ba28b
Create Date: 2025-05-15 17:20:03.621460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed9a97d65548'
down_revision: Union[str, None] = 'f69b556ba28b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('keywords', sa.String(), nullable=True))
    op.drop_index('ix_search_data_text', table_name='image', postgresql_using='gist')
    op.create_index('ix_search_data_text', 'image', [sa.literal_column("(text || coalesce(keywords, '')) gist_trgm_ops")], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_search_data_text', table_name='image', postgresql_using='gist')
    op.create_index('ix_search_data_text', 'image', ['text'], unique=False, postgresql_using='gist')
    op.drop_column('image', 'keywords')
    # ### end Alembic commands ###
