"""empty message

Revision ID: f69b556ba28b
Revises: 3a563e5b40e4
Create Date: 2025-04-30 17:02:37.793090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f69b556ba28b'
down_revision: Union[str, None] = '3a563e5b40e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('username', sa.String(), nullable=False))
    op.create_index(op.f('ix_channel_username'), 'channel', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_username'), table_name='channel')
    op.drop_column('channel', 'username')
    # ### end Alembic commands ###
